# Generated by Django 4.1.3 on 2022-11-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_todoitem_order_todoitem_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
    ]
